export default {
  root: '/',
  login: '/login',
  store: '/store',
  order: '/order',
  tables: '/tables',
  tableOrders: '/tableOrders',
  products: '/products',
  pickUpTables: '/pickUpTables',
  updateCategories: '/updateCategories',
  torderControl: '/torderControl',
  additional: '/additional',
  newProducts: '/newProducts',
  controlOrder: '/controlOrder',
  controlLastOrder: '/controlLastOrder',
  paymentManagement: '/paymentManagement',
  cancelPaymentOrder: '/cancelPaymentOrder',
  oldPaymentManagement: '/oldPaymentManagement',
  newPaymentManagement: '/newPaymentManagement',
  servingRobotManagement: '/servingRobotManagement',
  auctionManager: '/auctionManager',
  notice: '/notice',
};
