name: CI/CD development

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'label to deploy'
        required: true
        default: 'TORDER'
        type: choice
        options:
          - ALL
          - TORDER
          - BRAND1
          - UPLUS

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # 선택한 branch or tag 체크아웃
      - name: check out branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # 노드 버전 세팅
      - name: setup node version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # node_modules 설치
      - name: install dependencies
        run: yarn

      # node_modules 캐시 저장
      - name: save node_modules cache
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: node-modules-${{ github.sha }}-${{ github.workflow }}

  #---------------------------------- torder
  build_torder:
    if: ${{ github.event.inputs.label == 'TORDER' || github.event.inputs.label == 'ALL' }}
    needs: setup
    uses: ./.github/workflows/reusable_build.yml
    secrets:
      BUILD_COMMAND: origin:build:dev
      LABEL: torder

  deploy_torder:
    needs: build_torder
    uses: ./.github/workflows/reusable_deploy.yml
    secrets:
      TOKEN: ${{ secrets.BOT_PAT }}
      LABEL: torder
      AWS_ROLE_ARN: ${{ secrets.FRONTEND_ROLE_488659748805 }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_DEV_BUCKET_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  #---------------------------------- brand1
  build_brand1:
    if: ${{ github.event.inputs.label == 'BRAND1' || github.event.inputs.label == 'ALL' }}
    needs: setup
    uses: ./.github/workflows/reusable_build.yml
    secrets:
      BUILD_COMMAND: brand1:build:dev
      LABEL: brand1

  deploy_brand1:
    needs: build_brand1
    uses: ./.github/workflows/reusable_deploy.yml
    secrets:
      TOKEN: ${{ secrets.BOT_PAT }}
      LABEL: brand1
      AWS_ROLE_ARN: ${{ secrets.FRONTEND_ROLE_488659748805 }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_DEV_BRAND1_BUCKET_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DEV_BRAND1_DISTRIBUTION_ID }}

  #---------------------------------- uplus
  build_uplus:
    if: ${{ github.event.inputs.label == 'UPLUS' || github.event.inputs.label == 'ALL' }}
    needs: setup
    uses: ./.github/workflows/reusable_build.yml
    secrets:
      BUILD_COMMAND: uplus:build:dev
      LABEL: uplus

  deploy_uplus:
    needs: build_uplus
    uses: ./.github/workflows/reusable_deploy.yml
    secrets:
      TOKEN: ${{ secrets.BOT_PAT }}
      LABEL: uplus
      AWS_ROLE_ARN: ${{ secrets.FRONTEND_ROLE_488659748805 }}
      AWS_BUCKET_NAME: admin.share.torder.com
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DISTRIBUTION_ID: EAKRCUOX55TSQ
