name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize] # PR 생성, 재생성, 동기화

jobs:
  test:
    # 만약 PR에 gpt review 라는 라벨이 붙어있을때만 실행하고 싶다면 아래와 같이 작성하면 된다.
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-review') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # optional
          LANGUAGE: Korean # 한국어
          MODEL: gpt-4o-mini # gpt-4o-mini 가격 이슈로 4o-mini 모델을 PoC 로 사용
          PROMPT: 다음 프론트엔드 프로젝트의 코드 수정사항에 대해 코드리뷰를 해줘. 버그 발생 가능성, 성능저하, 잘못된 사용, 타입 불일치 등 다방면의 검토가 필요해
          max_tokens: 15000 # 15000 * 4(byte) / 3(byte) = 약 2만자의 순수 한글 피드백 가능 (1토큰 = 4byte)
          MAX_PATCH_LENGTH: 15000 # 이 임계점을 넘어가는 PR 은 리뷰하지 않음
          IGNORE_PATTERNS: /node_modules,.*\.(md|yml|svg|jpg|png|)$,CODEOWNERS,.gitignore,eslint.config.js,package.json,postcss.config.mjs, # Regex pattern to ignore files, separated by comma
