# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: PR Labeler
on:  # workflow를 trigger할 event
  pull_request: # main 브랜치에 pr이 open 되었을 때
    types: [opened]
jobs:
  label: # jobs 이름
    runs-on: ubuntu-latest # set runner
    permissions: # 해당 workflow의 접근 권한
      contents: read # 레포 내용은 읽기만 하고
      pull-requests: write # PR에 write할 수 있음!(github bot이 존재하니까!)

    steps:
      - name: Check Labels
        uses: actions/labeler@v4 # 우리가 사용한 action의 version
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}" # 자동 생성되는 token