name: FRONT 코드리뷰봇

on:
  pull_request:
    types:
      - opened
      - closed
  pull_request_review:
    types:
      - submitted
  pull_request_review_comment:
    types:
      - created

jobs:
  notify_pr_created:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.state == 'open'
    steps:
      - name: Notify PR Created
        uses: 8398a7/action-slack@v3.14.0
        with:
          status: custom
          fields: workflow, job, commit, repo, ref, author, took, pullRequest, message
          mention: "channel"
          if_mention: always
          custom_payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": ":urgent: Pull Request Opened :urgent:",
                        "emoji": true
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*프로덕트 :*\n마스터1"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*제목 :*\n${{ github.event.pull_request.title }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*생성자 :*\n${{ github.event.pull_request.user.login }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*브랜치 :*\n${{ github.event.pull_request.head.ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*병합대상 :*\n${{ github.event.pull_request.base.ref }}"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "PR 이동",
                            "emoji": true
                          },
                          "url": "${{ github.event.pull_request.html_url }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RACCOON_SLACK_WEBHOOK_URL }}

  notify_pr_approved:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review' && github.event.review.state != 'commented'
    steps:
      - name: Notify PR Review
        uses: 8398a7/action-slack@v3.14.0
        with:
          status: custom
          fields: workflow, job, commit, repo, ref, author, took, pullRequest, message
          mention: "channel"
          if_mention: always
          custom_payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": ":white_check_mark: ${{ github.event.pull_request.title }} 리뷰 승인 ",
                        "emoji": true
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*프로덕트 :*\n마스터1"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*리뷰어 :*\n${{ github.event.review.user.login }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*브랜치 :*\n${{ github.event.pull_request.head.ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*병합대상 :*\n${{ github.event.pull_request.base.ref }}"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "PR 이동",
                            "emoji": true
                          },
                          "url": "${{ github.event.pull_request.html_url }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RACCOON_SLACK_WEBHOOK_URL }}

  notify_pr_merged:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Notify PR Merged
        uses: 8398a7/action-slack@v3.14.0
        with:
          status: custom
          fields: workflow, job, commit, repo, ref, author, took, pullRequest, message
          mention: "channel"
          if_mention: always
          custom_payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "${{ github.event.pull_request.base.ref }} 내 병합 완료",
                        "emoji": true
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*제목 :*\n${{ github.event.pull_request.title }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*생성자 :*\n${{ github.event.pull_request.user.login }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*브랜치 :*\n${{ github.event.pull_request.head.ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*병합대상 :*\n${{ github.event.pull_request.base.ref }}"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "PR 이동",
                            "emoji": true
                          },
                          "url": "${{ github.event.pull_request.html_url }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RACCOON_SLACK_WEBHOOK_URL }}
