name: Sync fork with upstream

on:
  schedule:
    # 매일 자정에 동기화 작업을 수행
    - cron: '0 15 * * *'
  workflow_dispatch:
  # 수동으로 트리거할 수 있는 옵션

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # PERSONAL_ACCESS_TOKEN 이 설정되지 않았다면 더이상 진행하지 않음
      - name: Check if PERSONAL_ACCESS_TOKEN is set
        run: |
          if [ -z "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
            echo "Error: PERSONAL_ACCESS_TOKEN is not set"
            exit 0
          fi
        shell: bash

      # fork 된 리포지토리 체크아웃
      - name: Checkout forked repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # upstream 리포지토리 추가
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/torderdev/front-service.git
          git fetch upstream

      # upstream 브랜치를 fork 된 레포지토리의 master 브랜치로 병합
      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master

      # 병합된 변경 사항을 fork 된 리포지토리의 master 브랜치에 푸시
      - name: Push changes to forked repository
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
